spring:
  application:
    name: prize-draw-system
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 12939

security:
  jwt:
    secret-key: 0dac6e584cb74eae3468cd84ef70111987cfb0a52d726f780ddf761e93a17628
    expiration-time: 3600000