spring:
  application:
    name: prize-draw-system
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 12939

security:
  jwt:
    secret-key: 0dac6e584cb74eae3468cd84ef70111987cfb0a52d726f780ddf761e93a17628
    expiration-time: 3600000

token:
    bucket:
        capacity: 3.0
        refill-rate-per-second: 0.00567

promo:
  dynamic-rng:
    expected-daily-traffic: 10000
    min-probability: 0.005
    max-probability: 0.20

mailgun:
  from-name: "Pepsi Promo"